syntax = "proto3";

import "Protos/common.proto";

option csharp_namespace = "KuberManager.Contracts";

package kubermanager;

service SecretService {
  rpc Get (SecretRef) returns (SecretReply);
  rpc List (ListSecretsRequest) returns (SecretListReply);
  rpc Create (CreateSecretRequest) returns (OperationReply);
  rpc Delete (DeleteSecretRequest) returns (OperationReply);
}

message SecretRef {
  string cluster = 1;
  string namespace = 2;
  string name = 3;
}

message ListSecretsRequest {
  string cluster = 1;
  string namespace = 2;
}

message SecretReply {
  string name = 1;
  string namespace = 2;
  string type = 3;
  // values are automatically base64 encoded and decoded
  map<string, string> data = 4;
  string created_at = 5;
}

message SecretListReply {
  repeated SecretReply secrets = 1;
}

message CreateSecretRequest {
  string cluster = 1;
  string namespace = 2;
  string name = 3;
  string type = 4;
  // pass normal string, we will convert to base64
  map<string, string> string_data = 5;
  string requested_by = 6;
  string reason = 7;
  string correlation_id = 8;
}

message DeleteSecretRequest {
  string cluster = 1;
  string namespace = 2;
  string name = 3;
  string requested_by = 4;
  string reason = 5;
  string correlation_id = 6;
}
