# Bitta ClusterRoleBinding — kubermanager-sa ga kubermanager-cluster-role ni bog'laydi
# Bu barcha namespace'larda ishlashga ruxsat beradi
# Qo'shimcha xavfsizlik KuberManager'ning o'zidagi AllowedNamespaces policy orqali ta'minlanadi

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubermanager-cluster-rolebinding
  labels:
    app: kubermanager
subjects:
  - kind: ServiceAccount
    name: kubermanager-sa
    namespace: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubermanager-cluster-role
